### ISSUE TITLE
Fast Download

### ISSUE THREAD

**Issue by wkuzma** [VikingKampfsau/dynamic_mapvote#1]
Hi Viking
I want to inform you that the mapvote.iwd does change on the server after map change 
HOWEVER
it does not change on a fast download server and since the files are different it reverts to downloading from the server
making it take a very long time to download.
you have to somehow send the file to the fast download server for this to work good
even if I do not place the file on the fast download it reverts to the server for download.
prior to that problem I also had the problem here:
it only showed 2 maps to vote on even though it was set for 9 maps

**Comment by VikingKampfsau** [comment]
Hey,
I am sorry, but the tests i made were all on a local machine with the fastdl running on the same host.
The scripts & config are now updated and should work with fastdl servers running on a different host, please update your files.

The problem with only showing 2 maps instead of all 9 should also be fixed.
I removed the hardcoded item check from the menu and replaced it with a dvar inside the iwd.

Please report back if both bugs are fixed.
Thanks.

**Comment by wkuzma** [comment]
I posted this on cod4x.me but will repost it here:
 I just thought of some thing that may prevent the downloading of mapvote.iwd  on all maps
is it possible to rename mapvote.iwd to each map say something like mvcrash.iwd , mvconvoy.iwd  etc
then once its downloaded the next time the map comes up it will not have to be downloaded again? 
when I posted that it was just a thought.

Every thing else is working as it should.

**Comment by VikingKampfsau** [comment]
Sorry i never copied my answer from the cod4x forums to this place:

I don't think so because of some reasons:

- It would destroy the core intention of the vote -> predefined votes are not dynamic anymore
- Predefined votes would not consider all maps in your rotation, especially not when you change the runtime while the server is already running
- When the iwds are stored in the mod folder it's wasting a lot of space and at the end it would not work because of two reasons

1. the game stores all loaded iwds in a dvar that is used to check the hash to find out if it requires a (re-)download.
the lentgh of any dvar string is limited and might not cover all iwds in the end

1. the game loads iwds in alphabetical order, so the content of mvcrash.iwd is ignored when there is a mvconvoy.iwd

- When the iwds are stored outside the modfolder it won't work either because of the sv_pure dvar.
All clients with an additional iwd (let's say mvcrash.iwd) would be kicked when the server is using mvconvoy.iwd


I don't see a problem with the upload/download on every new map because the size of the mapvote.iwd is quite small.

With the original loadscreen images of cod4 stock maps i get a size of 3-4 MB which is nowadays a download of a few seconds.

If you want to lower the size you can change the resolution of the loadscreen images at any time.

Also, servers nowadays usually come without a traffic limit.

 

I agree that the short lag (connection interrupt) when the new iwd is zipped and uploaded is annoying, but to be honest i don't know how to tell the plugin to run the function as a new thread.

Maybe anybody knows and can fix this issue.

If not then that short lag should not really be a problem because for me it lasts about 1-2 seconds only at a point where it's not interrupting any gameplay.

 

Thanks for your feedback and suggestions so far :)
